### ISSUE TITLE
Invalid input is sometimes ignored by DecompressorWriter

### ISSUE THREAD

**Issue by jyn514** [dropbox/rust-brotli-decompressor#20]
```
; cat examples/compress.rs 
use std::io::{self, Write};

fn main() {
    let compressed = b"x";
    if let Err(e) = brotli_decompressor::writer::DecompressorWriter::new(io::stdout(), 1024).write(compressed) {
        eprintln!("{}", e);
    }
}
; cargo run --example compress -q; echo $?
0
```
Instead it should report an error that the input is invalid data.

**Comment by danielrh** [comment]
This, again, requires calling close() to initiate the flush, which would catch the error.
close was a private method before but it should be public now. Closing! Let me know if it gives any more trouble
