### ISSUE TITLE
Why not use `include_bytes!()` in dictionary?

### ISSUE THREAD

**Issue by stackinspector** [dropbox/rust-brotli-decompressor#25]
We can put binary content of dictionary directly into a separate file and simply `include_bytes!()` in the [source code](https://github.com/dropbox/rust-brotli-decompressor/blob/master/src/dictionary/mod.rs). Also, [huffman test](https://github.com/dropbox/rust-brotli-decompressor/blob/master/src/huffman/tests.rs) cases can be serialized into simple binary format. Separation of code and resources is a good paradigm. This may also improve maintainability, and people who run the LOC count on this codebase will not be surprised (I was surprised).
If you maintainers agree with this, I'm glad to PR with these changes.

**Comment by danielrh** [comment]
I think one of the goals was to keep it similar to the C source.
Also: these are baked into the standard, so I don't envision them changing very often... I'm not sure separating them out add too much value at this point.
