### ISSUE TITLE
No clear decompression completed signal

### ISSUE THREAD

**Issue by Augustyniak** [dropbox/rust-brotli-decompressor#28]
`brotli::Decompressor` doesn't inform developer of when all of the input data is decompressed. Per https://github.com/dropbox/rust-brotli-decompressor/blob/0045b6e18a91b12937ffc45a7a4f934ffeab7d2e/src/reader.rs#L303-L304 `decompressor.read` is never called with `Ok(0)` result which makes it impossible for the user of the API to figure out when the decompression of the input data is done. 

**Example**

The decompressor of the following type is set up:
```rust
brotli::Decompressor<bytes::buf::Reader<BytesMut>>
```

The decompressor is initialized:
```rust
brotli::Decompressor::new(BytesMut::new().reader(), 4096)
```

And the following logic is implemented to decompress data:
```rust
let mut out_bytes_buf: BytesMut = BytesMut::new();

loop {
  if bytes_written + 4096 >= out_bytes_buf.len() {
    out_bytes_buf.reserve(4096);
    unsafe {
      out_bytes_buf.set_len(out_bytes_buf.capacity());
    }
  }

  let out_bytes = out_bytes_buf[bytes_written ..].index_mut(0 .. 4096);

  match self.decompressor.read(out_bytes) {
    Ok(count) => {
      bytes_written += count
      log::error!("Ok({count}), bytes_written: {bytes_written}");
      if count == 0 {
        // that would be a clear "decompression completed" signal but it never comes.
        break;
      }
    },
    Err(e) => {
       // Instead of `Ok(0)` the `Err(std::io::ErrorKind::InvalidData)` call is made.
       log::error!("error while decompressing: {e}");
    },
  };
}
```

An example output of the program:
```
Ok(4091), bytes_written: 8192
Ok(4096), bytes_written: 12288
Ok(2727), bytes_written: 15015
error while decompressing: Invalid Data
```

The proposal would be to change `DecompressorCustomIo`'s default behavior to not return an error for cases when `count == 0`. That would probably break some of the clients of the current API so maybe the alternative would be to give developers an option to specify what `DecompressorCustomIo` should do with `Ok(0)` cases in here https://github.com/dropbox/rust-brotli-decompressor/blob/0045b6e18a91b12937ffc45a7a4f934ffeab7d2e/src/reader.rs#L303-L304 - always returning an error does not seem to be "fits-it-all" solution. With the current implementation the only way to detect the completion of decompression is to check for error that's equal to `std::io::ErrorKind::InvalidData` that's currently set up in https://github.com/dropbox/rust-brotli-decompressor/blob/0045b6e18a91b12937ffc45a7a4f934ffeab7d2e/src/reader.rs#L45-L46.

Also, `DecompressorCustomIo`'s `new` method does not allow to create `DecompressorCustomIo` with `error_if_invalid_data` set to `None`:
https://github.com/dropbox/rust-brotli-decompressor/blob/0045b6e18a91b12937ffc45a7a4f934ffeab7d2e/src/reader.rs#L207-L227

**Comment by danielrh** [comment]
Hopefully this is a way to signal to the reader that there were additional bytes, without changing the compatibility too much.
The other option is to build your own custom reader directly out of the raw stream interface to brotli.

https://github.com/dropbox/rust-brotli-decompressor#whats-new-in-version-240
